backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "accounts"
    label: "Accounts for Sale"
    folder: "content/accounts"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    identifier_field: "title"
    fields:
      - { label: "Title",        name: "title",        widget: "string" }
      - { label: "Price (USD)",  name: "price",        widget: "number" }
      - { label: "Description",  name: "desc",         widget: "text" }
      - { label: "Preview Image",name: "previewImage", widget: "image" }
      - label: "Additional Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
