backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "accounts"
    label: "Accounts for Sale"
    folder: "content/accounts"
    create: true
    slug: "{{slug}}"
    format: "json"   # important: save as JSON
    extension: "json"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price (USD)", name: "price", widget: "number" }
      - { label: "Description", name: "desc", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
